### ISSUE TITLE
Question about the accuracy calculation 

### ISSUE THREAD

**Issue by frankhlchi** [zwt233/ALG#2]
Hi there,

Thank you for making the code public. When I was reading the Test.ipynb about the final performance on the citeseer dataset. I was a bit lost about how to get the final reported accuracy of 73.6.

As shown in the notebook, after 17 runs, the corresponding testing accuracies are printed out at the end of notebook:
```
[0.651,
 0.668,
 0.651,
 0.666,
 0.705,
 0.6880000000000001,
 0.6970000000000001,
 0.715,
 0.7000000000000001,
 0.727,
 0.712,
 0.721,
 0.736,
 0.729,
 0.746,
 0.74,
 0.724]
```
Does the final accuracy are calculated by taking the average of the top 5 performers in the list? Thank you!

**Comment by zwt233** [comment]
Thanks for your attention. We print "test_accs" to show the performance changement during the labeling process. The corresponding testing accuracies in the "test_accs" are not the results for 17 different runs. 
As shown in the 18th code block, "test_accs"  just records the test accuracy when we label nodes in each batch. In other words, this notebook just shows the results in one run.

**Comment by frankhlchi** [comment]
Thank you for your quick response. So, in this run, is testing accuracy equal to 0.726 shown in block 21?
```
Optimization Finished!
Total time elapsed: 3.4873s
0.726 0.726
```

**Comment by zwt233** [comment]
> Thank you for your quick response. So, in this run, is testing accuracy equal to 0.726 shown in block 21?
> 
> ```
> Optimization Finished!
> Total time elapsed: 3.4873s
> 0.726 0.726
> ```

Yes, the final result of this run is 0.726. The variance of accuracy is large. For example, as shown in block 21, we can get a test_acc 0f 0.745 or 0.726 with the same val_acc of 0.726. So, we report the mean accuracy of multiple runs to eleminate the randomness.

**Comment by frankhlchi** [comment]
Got it. Thank you for the clarification!
